### ISSUE TITLE
Incompatibility with Preact

### ISSUE THREAD

**Issue by yannbf** [code-hike/codehike#272] opened 2022-08-22 08:34 UTC
**Edit: it was discovered that the issue is actually an incompatibility with Preact**

Hello 👋 

I really really love this lib, thank you so much for implementing it! I switched the snippet lib in my blog to use CodeHike and it looks great, there's only one unfortunate side effect.. sometimes the code is not visible after resizing, or when I visit my website on mobile and scroll back and forth:

<img src="https://user-images.githubusercontent.com/1671563/185876598-17f8b0b9-5209-4eba-81a2-8221d30a03ae.png" height="600" />

I don't know exactly what's going on, but I see that there are inline changes in the element which change its properties, including `opacity`, which makes things "invisible":

![2022-08-22 10 29 41](https://user-images.githubusercontent.com/1671563/185876367-1872ec60-bc01-42ea-bdfc-fd6ef283c12b.gif)

[Here's the website](https://yannbraga.dev/blog/multi-theme-decorator) in question. 

I'd love to get some light on what could be causing it. Thank you so much!

**Comment by pomber** [comment] 2022-08-22 08:49
Interesting, I haven't seen that. What Code Hike version are you using? is the blog open source?

**Comment by yannbf** [comment] 2022-08-23 15:18
Thanks for the quick answer @pomber! The version is 0.7.3 and yes it's [open source](https://github.com/yannbf/braga.dev/).

**Comment by pomber** [comment] 2022-08-23 16:40
Thanks. I'll take a look later. 

If you can provide a smaller project reproducing the issue it would help us find the problem faster.

**Comment by pomber** [comment] 2022-08-27 08:48
I think I've found the problem. You are using preact for the production build, I haven't tested Code Hike with preact yet. 

Let me know if you can confirm that's the problem. Next week I'm going to see how hard it is to make Code Hike compatible with preact, it may be an easy fix.

**Comment by yannbf** [comment] 2022-08-27 09:35
@pomber that was it. You're the best!! Thank you so much for that info, and sorry for the trouble.
I renamed the issue, though honestly feel free to close it, I don't really expect you to bring preact compatibility to this library. 

Honestly this made me realize how weird practice it is to use React on dev and ship Preact on prod, which can lead to puzzling production issues like these. I'm now always using React.

Thanks a lot once again, have a wonderful weekend!

**Comment by pomber** [comment] 2022-08-27 10:27
Thanks. I also think it's risky to switch to preact in prod. But as far as I know, preact should work with code hike since we aren't using anything incompatible.

I think I found the problem, but it looks like a preact bug to me: https://github.com/preactjs/preact/issues/3695. Let's wait for their answer.

**Comment by pomber** [comment] 2022-10-08 10:34
> I think I found the problem, but it looks like a preact bug to me: [preactjs/preact#3695](https://github.com/preactjs/preact/issues/3695). Let's wait for their answer.

Fixed in [Preact v10.11.0](https://github.com/preactjs/preact/releases/tag/10.11.0)

**Closed by pomber** 2022-10-08 10:34 UTC
