### ISSUE TITLE
CH.Slideshow throws an error when there is no code block for a slide

### ISSUE THREAD

**Issue by brianespinosa** [code-hike/codehike#227] opened 2022-07-21 04:35 UTC
It would make more sense if we could just render whatever the MDX is for the slide instead of the code hike code/example in the north pane in any scenario where there is no code block. This might give the option for others to create slides in between a code walkthrough.

I think the challenge might be that we are parsing the contents of a slide and anything outside of a code block is being interpreted as a slide note. My suggestion above might only be possible if we made a change to how the slide notes were parsed. One possibility would be having a CH.SlideNotes component to contain them in a slide, or possibly by adding frontmatter support per slide.

**Comment by pomber** [comment] 2022-07-21 08:13
Missing code shouldn't throw an error anymore since `v0.7.0-next.2`.When a step doesn't have code it shows the code from the previous step. 

But that's probably not what you are suggesting. Can you provide a small example to see if I understand?

**Comment by brianespinosa** [comment] 2022-07-21 14:51
The fix in 0.7.0 RC2 is what I need. Thanks! I'll keep an eye out for the next minor release.

Admittedly... this was a bug report with a hidden feature request attached to it. I must have put on my product hat last night.

**Comment by brianespinosa** [comment] 2022-07-22 18:17
I saw 0.7.0 was released and updated locally and I am still seeing the issue, though I suspect it may be because I am using `next-mdx-remote` in my implementation. Let me dig a bit more today and I should be able to also share some working examples of what I am seeing with a public repo.

Thanks for all your work on codehike btw. Great stuff.

**Comment by pomber** [comment] 2022-07-26 18:28
Maybe try to reproduce it in the playground: https://play.codehike.org/

**Comment by brianespinosa** [comment] 2022-07-27 21:51
@pomber Yes, [I was able to reproduce](https://play.codehike.org/#N4IgtgJgHiBcIB0B2AeAwgCQHQGUA2AlhAKYDOAFgPYDuAfMsgCrkGkAEphJb5Ahu0kpsAxpW4AjPJWEBrLAyQBaZQoAG6gFakobAGbSArqQC8AFmQEwAB0oAnAC5sASsV7DHu25TBsA5Ldd3XwBuC2s7Rxc3ewARAHkAWT0vH39A+0UIbwB6YUJiJHsQhVEkUkdeKys2YzYUcgBGDnsATzxiY2BgEUopW1g-e1c8XzYAXzHaDGI8KWd0lGzG2lCkZFLyti9KR1qo93iErGEA3iGnSh2ACizhAzAC+ywAc2J7AFF2h8KAIRaASQgV38lyKAEowattk8AkgSLYrpUrJDkOpVAofgZHAQykNeBA2JRdGwjDjniJTkNPsRvo4IAQAu48C02C1KAYRLwkCTSMQ2AApHAADXkayUKjFaK0On0dxMplgDQADGEbA55tFkt4-KcgqtLGrIulDlrUrqMlkwLl8oVimLdAYkO4CJRuQkWmhvDYkI8rmC2MBkGwtm8DLZuVcg8G6vSAG70bnR4MocRY+yuqYzKSLVP2dNIBNJxZxwtsFFIMYlV2bJE1OqNZptDpdHp9Aa+PEjcaTaazIT7eyLZardbVxzQusDw7HSnEC7XW73R4vN7U2l-QHA6G+CFQ0FYWHwxFVctohSMIQnVxDNi8HrhH2FVnswlIZlsH3EAnptjUWwEG87wdJ17BdblqAA8hbw-XgHjYew+EccpeAcdgIIQ6DhEqADeDwNh2jzYhbFFZBlEUNRNG0PRDHlABtZVYAAJiVABdAAaBpGMVAB2VUIg1dxTR1dI7QNfip0SIS0miTIcjyAhHjtZBgOdV02HdT0H19f1A0TAJ7DDCMo2TEtjOjFM0wzXts2yXN81LZNslMxNy0rMUNgqKo60jRMUGcosNK9V1HjYbIHLqQKtKfMKo2LAh42QctR1xLZQUnY1Ehna851BG5DFpFcPi+R4NyBEEdh3ctoQPAojyRU91AUAA5Ghnw5LDuSMPkELOPRHVU7kcQFYUSPFcjJUomUaOMBpTHogAOJiAE52IaABWBbYAAZgaFi+PVAcpPNUTwgOjKkk8bVpPcWSrXkxSRyQFTQLUyLvW0gMo30wy2B8ot-KTOo7KsrNKBzSyCzMuKEpc1Y3OSmsvNqP6Y3i8KUDe4KnyQWCOgQEAEhQ0CfVmAh8dC9HMcfRwcYeYx8f5MgjHJmLfKctHEsejzUp2dLomnK8zhyhd8uXV4ippEqATK7dd2QarDyI49kVWM8xQATRfDrb1IUgCGebkznsf9czIBQyIo1RpWouUzFoxiuMYlaOLmhpFqd1aNrd7bdv2o1NUus0RP1U7-YOSTA+EmTLWtBTbUe56wPUj0gupq5ulpvkxh0r7Q3DX6oYBotgYLaywdsiH0fZmHg1cqsUtrZHYqLiKU6imncfpgmiZxLMyZACmoapkLM67xnSGZgfWcc5ykqdMced2ATYkywXzlyxcCvFtcpc3crwSq-dFYRerVcasUAEE4WX38CFmNgrH4dgEJpeChBf+93qffgH5Q3GhlsKQc2EpUSTRtkYO2DtlrsV4kgMSZ0A4pCjnqP2y8TSR2uhaOSNoigJ36i9N0bcv72HTjBOC2dPp6TzkZRMJkOa0PMiXWgwBM5jHBnmDMUNq6ljru5BejcC6+RbhjIhWMO503xoTBwvdSYs0pqI6mZC8YgHHpPQebNZ5cwXhOPY50spC3nCQzeYtVzFV+NLLcoJKp7h2DVOEStT6gPRGKf4ZQiB8kFEKNibUeR8juLYd84hbBuDIG-X8wTqgQBaLTAgwg2AQDOLwYB40nHW1lBAtabElqoMOhg46IdDRoIjkgzBt1Y4PQUInV6CjfQZ1xuMHOiZubPEoLhT0jol6MVWMGb6+cUZ0JroDCyHCCwsNxmwiuIzwrBmAL4QAvWS+BqlYa8VwWltPZIUMEbkizcKjLwhGnlqhNyEfQgKNTsad0kT3EmhA5FD3OeI5RqigFT1LNDBMc9uY6KKUcNewsjGi0KIVHe5i96y0PrY4+ysGrOOQK4vQmo2TtS5OEyot4kAsg0LwWM-ATgECsI4YgUArABF1mBUaFsJpWyoukkw3FYBLQ4lteia1tprT2nA0ON88nBxyedI66Qyn3XjpU-BSdh6FFIZnBplDgzNNaXgdpT5ahdIUHKhefA4TtDQIQWQ3liCxkeP6YwtBZXRmyNkeJQhSDeDeCwJAzwoxjEej06hgj-qnKGSXV8OrYkyE6JqiA2rdUyEmGMh4EymFmRmfMxZARllnFWQqpV9gtlcIBvs+eDckbutRoM5MErHldykcTPudyGEiM0sQpRY8mYvPUTPehnztFpV0fzVes5DF5TuFvUxktQUyysXLJACtaoOJPGfWFSALy3ggASA1IVCDlAKERdgSLf662glU7kP4P6iFsKS709IHW3jzCbLExBkmWzSdNNafLEFXXyfe8OF0SnmiFTgpST0xXVKrWIqV9SKG6XVSlWiazFUbPsN43k9gU0sT5u4LAXUcD2CFlcRic8QObEDcGv1+rDWbJqKa4D5rLVZA4LahCZInXdJDAZPphdPXFwhj6kNAauRBuIL62QYbWHsPstGgMsalkrPAymtNFbdmw2QPDLNiMjm5r8kx1uf7FGjyudIm5-cG3mULTWhmdby2Nphs2lK3yJK-M7RvQFTxt5mPsKVSxFVh2jvsSfCdTjzxCHxASZCN4fx3lEO3eC5AiLEF8M-ULviUNCz6iBJOkcBwUpAUgKUNLb1sXpdkzlhTclvt5Tl8S-KeXR2wXHXBor4u-tTrUpRMqSPczA8myD0G3hwYQ08ZDqGhjocwz0FKOGuMhvw0aojZrgwwZTUm9ZHS2AAGo2ANHLMGZ1aq6M-X6Xm6ZQMWOum4-64Ag39u8fGfxzhDCY0LJE4msTkGJM7IzXDeu8nvLN2U5WmrFyJHd002W159zVMj0uSowz-2NFNq0WZ1tPz9HrxFj2kxEt1wWP3tY+WR8x3uZVp5lxjhnjxVCeuoCP6d1CAMFYBJ-mot+eIMllJqWwG0uMJkrLTKXaWwUAAdVC9yddWF74AW8YdCC98ZCCGoGwACH5iBfmfkIAIihj4hb8Z9p4V6qU3ttg0bL8Cw4eHy9EE6uXisG5ujHYVFX7Qk+ToDyVdTyGNKw44JrM3Citdg5B+DbbENdbQxhl1-XsMcdw3q5GC7CMmvGxwNrkHpsQdmwtpbtHVtildfRmhHr82MN20gfb7GtVDb9SdiNZ3IYXaE1d+NonmsdPu+ZKTtcnt8JSlYPAvAWirrrLRXwJaZGEF8N43wzyB9+B+LhSgzxHS+BYpDl7xyBnyNt0WjTpbZFg7OUv-TIOJ71unnUKTpnNjmb0X8rtxigV2f7Q5lH4KbEwkx9CydXmQxuegku+w6vUnpa14yxizKABs20pg7EjEpgbEjEXssA-+HKuu3KpulusBFmAqpWd0n6eCVWhCS+AGDuZqjWt2HS7u7W3unWvIMWPW-ua23MR2w2YeBGqaY2JGE2MeHSceKa82i2y24wAevSGe5kLcyY3qe2bGh2wehePGzCfGkyAm5esylexACaJC+Bmy2y9ej2Mmz2jgre7enetQ3eveWmI+Q+dahhY+Ugk+SA0+s+hyr2JyWewAWhHegCWAYAlQVwVwDhRETUuMxqpqm2BaDyNa9hbejhXhEabAMgxALQnQHhtgoRxAYwOmtcde7ynMGhi8HWAsVm8OS4F+fayOYKQ6EK9+bmj+OOyAfOKKLh1QgQUE7+kuQwPgAW3IMwV+PIZIbAWKOKpAeKBKdO163+ECoBtEW0i0a0wBHOYoh0ro74n4EA7Ad4joBAAAjgYHyBESyPoLYGwDUdsfZt4j+LoDiASOyI4NQDzhRg8FRiesIJqq8KQH0RrgMSYIxA0ExNxGxFtEqB8eYIVggoJCVigr8XrugvAR+uVl+tujbqrtgVnI7oHs7koVBtHh7h0l7svEhqQd1sQL1gHlQaIftiNhHsRmZJNrHoiewUnjRmtjwbmgvoJsMvmKxn6vnpxsdhIadlIedoDBXnGvIdXq7qmiocZjwk3gcg-METoWwHodcn3IYcPoPqYRPlPjPpVgNMnD8JQFAH6GajSUprGI2O0J0N0OIHYPCO2PNFYDoDalwPEjLlUDiDIKMBMLQBamwIwHEPEBcXamSO8qKXJtYfPq3BqVAOFEEdoU4VUW4TEXET4bSbpgEaPGGSEeMuEZEdERKbESmXvkkSoYsO6MGR8lYekcQZkdlGfjZsCvZo5qji5hjiUY4gzlOv8MSOutQFyI4D+EFjYLyJ-GInLuLKFrYJ-o2ZroMQ0PRIAYxNxCAWAZ8UAc+vro+gVogSbkuSgeUiKlbhgVCe3DCfVlGHgTXm7siUQeib7uQX1niQXgSbQaNpHowSeWSUeY4InpwSnrnOnnGXqdtgyWpEIcySIdeSGsXvEaXttrIbyQoawXdkKfvmoRWGkTEewLoT3jKaTHKcYQqePuYZYaqQQuqZqaQjcXfBALCPuVQp+XqQac2MaaaUROaZaRRjaSQPIVYA6U6WGsRXgKRQUBMiWH6dzAIijCIgWWZEmaus4a4e4RmTGWNn4SpqroEdGSmesemeGXEQkdmWWMkdkPmZqYWWkcfu2pZmWdZgjrkUjrvIOs5kUXYnVB5o2QoIdI-LrKEh-D6MuvOvZuwDiHrNwHeKQMssIAQLhA-F4Msg4CyPzu0ASFxTxUgKNIsJgLgFwGQFQHQMgCAGxCAMILrHACAFgCSgagpNQIoKUKhr3Fsd0FGC4bYPjkgAMBaVAMEGwDJllTla6Icc8HAKAIQD6E1PcOIKunALoLhLyNlRQDQJ6FYC0JiCMiNWNcQNlS-A8PlS4QAiFXgJkChBEbYCABMEAA) and turns out I guess that this is expected, at least in the first slide as the error message "The first step should have some code" is in [steps.tsx](https://github.com/code-hike/codehike/blob/ed3116e031aa30d5920a5587594ac8e1e5d4e685/packages/mdx/src/remark/steps.tsx#L142)

**Comment by pomber** [comment] 2022-07-28 08:29
Yes, that's intended, if a step doesn't have code it uses the code from the previous step. 

I'll close this one. If that error still blocks your use case, feel free to create a new issue.

**Closed by pomber** 2022-07-28 08:29 UTC
